# Matrix Decomposition

In [1]:
import numpy as np

## Eigen Decomposition

$$\mathbf{A}\vec{x} = \lambda \vec{x}$$

where:
* $\vec{x}$ is the Eigen vector
* $\lambda$ is the Eigen values

$$\mathbf{A} = \mathbf{Q} \, \text{diag}(\lambda) \, \mathbf{Q}^{-1}$$

where $\mathbf{Q}$ is the orthogonal Eigenvector matrix.


Example:

Take matrix $\mathbf{A}$, find the Eigen values and Eigenvector matrix!

In [2]:
A = np.array([[4, 1],
              [2, 1]])
A

array([[4, 1],
       [2, 1]])

In [3]:
e, Q = np.linalg.eig(A)

print("Eigen values = ")
print(e)

print("Eigenvector matrix = ")
print(Q)

Eigen values = 
[4.56155281 0.43844719]
Eigenvector matrix = 
[[ 0.87192821 -0.27032301]
 [ 0.48963374  0.96276969]]


Compute $\mathbf{Q} \, \text{diag}(\lambda) \, \mathbf{Q}^{-1}$. Show that the resul is $\mathbf{A}$.

In [4]:
Q@np.diag(e)@np.linalg.inv(Q)

array([[4., 1.],
       [2., 1.]])

## SVD Decomposition

$$
\mathbf{A}=\mathbf{U} \mathbf{\Sigma} \mathbf{V}^T
$$

where:

* $\mathbf{U}$ is an orthogonal matrix
* $\mathbf{\Sigma}$ is an rectangular diagonal matrix
* $\mathbf{V}$ is an orthogonal matrix


The SVD of $\mathbf{A}$ is closely related to the eigendecompositions of $\mathbf{A} \mathbf{A}^T$ and $\mathbf{A}^T \mathbf{A}$
- The left singular vectors are the eigenvectors of $\mathbf{A A}^T$
- The right singular vectors are the eigenvectors of $\mathbf{A}^T \mathbf{A}$
- The singular values are the square roots of the eigenvalues of both $\mathbf{A A}^T$ and $\mathbf{A}^T \mathbf{A}$


### Example:

Example:

Take matrix $\mathbf{A}$, find the SVD decomposition!

In [5]:
A = np.array([[4, 1],
              [2, 1]])
A

array([[4, 1],
       [2, 1]])

In [6]:
U, S, V = np.linalg.svd(A)
print("U = ")
print(U)

print("S = ")
print(S)

print("V = ")
print(V)

U = 
[[-0.8816746  -0.47185793]
 [-0.47185793  0.8816746 ]]
S = 
[4.6708301  0.42818941]
V = 
[[-0.95709203 -0.28978415]
 [-0.28978415  0.95709203]]


In [7]:
U@np.diag(S)@V.transpose()

array([[4., 1.],
       [2., 1.]])

## SVD Decomposition of a Square Symmetric and Positive Definite Matrix

A square matrix is called positive definite if it is symmetric and all its eigenvalues $\lambda$ are positive, that is $\lambda > 0$.

Additionally, if $\mathbf{A}$ is positive definite, then it is invertible and $\det(\mathbf{A}) > 0$.

For square symmetric and positive definite matrix:

$$\text{eig}(\mathbf{A})  = \mathbf{\Sigma} $$

Example, take matrix $\mathbf{A}$, show that its SVD decompositoin is equal to its Eigen decomposition.

In [8]:
A = np.array([[2, 1],
              [1, 1]])

U, S, V = np.linalg.svd(A)
e, Q = np.linalg.eig(A)



In [9]:
print(S)
print(e)

[2.61803399 0.38196601]
[2.61803399 0.38196601]


In [10]:
print(U)
print(V)
print(Q)

[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
